apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  namespace: go-namespace
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-pod
        image: "shivangani/go-app:{{TAG}}"
        ports:
        - containerPort: 80
