apiVersion: v1
kind: Service
metadata:
  name: my-service-go
  namespace: go-namespace
spec:
  selector:
    app: go-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort


